impasta/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('restaurants/',  views.RestaurantList.as_view(), name="restaurants_index"),
    path('accounts/signup/', views.signup, name='signup'),
    path('restaurants/<int:pk>/', views.RestaurantDetail.as_view(), name='restaurants_detail'),
    path('restaurants/<int:restaurant_id>/menu/<int:pk>/', views.MenuItemDetail.as_view(), name='menuitems_detail'),
    path('recipes/<int:pk>/', views.RecipeDetail.as_view(), name='recipes_detail'),
    path('recipes/create/', views.RecipeCreate.as_view(), name='recipes_create'),
    path('recipes/<int:pk>/update/', views.RecipeUpdate.as_view(), name='recipes_update'),
    path('recipes/<int:pk>/delete/', views.RecipeDelete.as_view(), name='recipes_delete'),
    path('recipes/<int:recipe_id>/add_instruction/', views.add_instruction, name='add_instructions'),
    path('recipes/<int:recipe_id>/add_ingredient/', views.add_ingredient, name='add_ingredients'),
    path('ingredients/<int:ingredient_id>/delete/', views.delete_ingredient, name='ingredients_delete'),
    path('instructions/<int:instruction_id>/delete/', views.delete_instruction, name='instructions_delete'),
    path('recipes/<int:recipe_id>/add_review/', views.add_review, name='add_reviews'),
    path('reviews/<int:review_id>/delete/', views.delete_review, name='reviews_delete'),
    path('search/', views.search_result, name='search_results'),
]

main_app/models.py
from ctypes import addressof
from pydoc import describe
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

# Create your models here.
class Restaurant(models.Model):
    name = models.CharField(max_length=100)
    address = models.TextField(max_length=250)
    phone = models.CharField(max_length=20)
    cuisine = models.CharField(max_length=20)
    desc = models.TextField(max_length=1000)
    img = models.CharField(max_length=250)

    def __str__(self):
        return f'{self.name} ({self.id})'


class MenuItem(models.Model):
    name = models.CharField(max_length=250)
    course = models.CharField(max_length=250)
    price = models.FloatField()
    desc = models.TextField(max_length=1000)
    img = models.CharField(max_length=250)
    restaurant = models.ForeignKey(
        Restaurant, 
        on_delete=models.CASCADE
    )

    def __str__(self):
        return f'{self.restaurant.name}\'s {self.name}'



class Recipe(models.Model):
    name = models.CharField(max_length=250, verbose_name="Recipe Name")
    img = models.CharField(max_length=250, verbose_name="Image URL")
    time = models.CharField(max_length=250, verbose_name="Prep Time")
    tags = models.CharField(max_length=250, verbose_name="Tags")
    menu_item = models.ManyToManyField(MenuItem, verbose_name="Related Menu Item(s)")
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE
    )
    
    def get_absolute_url(self):
        return reverse('recipes_detail', kwargs={'pk' : self.id})
    
class Instruction(models.Model):
    order = models.IntegerField()
    step = models.TextField(max_length=2500)
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE
    )
    recipe = models.ForeignKey(
        Recipe,
        on_delete=models.CASCADE
    )

class Ingredient(models.Model):
    name = models.CharField(max_length=250)
    quantity = models.CharField(max_length=250)
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE
    )
    recipe = models.ForeignKey(
        Recipe,
        on_delete=models.CASCADE
    )

class Review(models.Model):
    RATINGS = (
        (1, '1'),
        (2, '2'),
        (3, '3'),
        (4, '4'),
        (5, '5')
    )
    rating = models.IntegerField(default=5, choices=RATINGS)
    comment = models.TextField(max_length=2500)
    recipe = models.ForeignKey(
        Recipe,
        on_delete=models.CASCADE
    )
    user = models.ForeignKey(
        User, 
        on_delete=models.CASCADE
    )

main_app/forms.py
from django.forms import ModelForm
from .models import Instruction, Ingredient, Review

class InstructionForm(ModelForm):
  class Meta:
    model = Instruction
    fields = ['order', 'step']

class IngredientForm(ModelForm):
  class Meta:
    model = Ingredient
    fields = ['quantity', 'name']

class ReviewForm(ModelForm):
  class Meta:
    model = Review
    fields = ['comment', 'rating']

main_app/views.py
from distutils.log import Log
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.db.models import Avg
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from operator import itemgetter
import requests
from urllib.error import HTTPError
from urllib.parse import quote
from urllib.parse import urlencode

from .models import Restaurant, MenuItem, Recipe, Ingredient, Instruction, Review
from .forms import InstructionForm, IngredientForm, ReviewForm

# Create your views here.
def home(request):
    # fetch_data()
    restaurants = Restaurant.objects.all()[:5]
    recipes = [{
            'id':recipe.id,
            'name':recipe.name,
            'img':recipe.img,
            'avg_rating': recipe.review_set.all().aggregate(Avg('rating'))['rating__avg'] if len(recipe.review_set.all()) else 0
    } for recipe in Recipe.objects.all()]
    recipes = sorted(recipes, key=itemgetter('avg_rating'), reverse=True)[:5]
    return render(request,'home.html', { 
        'restaurants':restaurants,
        'recipes':recipes,
    })

class RestaurantList(ListView):
    model = Restaurant
    fields = '__all__'

    def get_context_data(self, **kwargs):
        context = super(RestaurantList, self).get_context_data(**kwargs)
        context['cuisines'] = ['American','Chinese','Indian','Italian','Other']
        return context

def signup(request):
    error_message = ''
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('home')
        else:
            error_message = 'Invalid sign up - try again'
    form = UserCreationForm()
    context = {'form': form, 'error_message': error_message}
    return render(request, 'registration/signup.html', context)


class RestaurantDetail(DetailView):
    model = Restaurant
    fields = '__all__'


class MenuItemDetail(DetailView):
    model = MenuItem
    fields = '__all__'

    @property
    def menu_item(self):
        return self.kwargs['pk'] 

    def get_context_data(self, **kwargs):
        context = super(MenuItemDetail, self).get_context_data(**kwargs)
        recipes_set = MenuItem.objects.get(id=self.menu_item).recipe_set.all()
        recipes = [{
            'id':recipe.id,
            'name':recipe.name,
            'img':recipe.img,
            'time':recipe.time,
            'avg_rating':recipe.review_set.all().aggregate(Avg('rating'))['rating__avg']
        } for recipe in recipes_set]
        context['recipes'] = recipes
        return context

class RecipeDetail(DetailView):
    model = Recipe
    fields = '__all__'

    def get_context_data(self, **kwargs):
        context = super(RecipeDetail, self).get_context_data(**kwargs)
        context['instruction_form'] = InstructionForm()
        context['ingredient_form'] = IngredientForm()
        context['review_form'] = ReviewForm()
        return context


class RecipeCreate(LoginRequiredMixin, CreateView):
    model = Recipe
    fields = ['name', 'img', 'time', 'tags', 'menu_item']
    success_url= '/recipes/'
    login_url = 'signup'

    def get_success_url(self) -> str:
        return f'/recipes/{self.object.id}'
 
    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

class RecipeUpdate(LoginRequiredMixin, UpdateView):
    model = Recipe
    fields = '__all__'
    login_url = 'signup'

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

class RecipeDelete(LoginRequiredMixin, DeleteView):
    model = Recipe
    success_url = '/'
    login_url = 'signup'

@login_required
def add_instruction(request, recipe_id):
    form = InstructionForm(request.POST)
    if form.is_valid():
        new_instruction = form.save(commit=False)
        new_instruction.recipe_id = recipe_id
        new_instruction.user = request.user
        new_instruction.save()
    return redirect('recipes_detail', pk=recipe_id)

@login_required
def add_ingredient(request, recipe_id):
    form = IngredientForm(request.POST)
    if form.is_valid():
        new_ingredient = form.save(commit=False)
        new_ingredient.recipe_id = recipe_id
        new_ingredient.user = request.user
        new_ingredient.save()
    return redirect('recipes_detail', pk=recipe_id)

@login_required
def delete_ingredient(request, ingredient_id):
    ingredient = Ingredient.objects.get(id=ingredient_id)
    recipe = ingredient.recipe
    if request.user == ingredient.user:
        ingredient.delete()
    return redirect('recipes_detail', pk=recipe.id)

@login_required
def delete_instruction(request, instruction_id):
    instruction = Instruction.objects.get(id=instruction_id)
    recipe = instruction.recipe
    instruction.delete()
    return redirect('recipes_detail', pk=recipe.id)

@login_required
def add_review(request, recipe_id):
    form = ReviewForm(request.POST)
    if form.is_valid():
        new_review = form.save(commit=False)
        new_review.recipe_id = recipe_id
        new_review.user = request.user
        new_review.save()
    return redirect('recipes_detail', pk=recipe_id)

@login_required
def delete_review(request, review_id):
    review = Review.objects.get(id=review_id)
    recipe = review.recipe
    review.delete()
    return redirect('recipes_detail', pk=recipe.id)

def search_result(request):
    search_term = request.GET.get('q', '')
    recipes_tags = Recipe.objects.filter(tags__icontains=search_term)
    recipes_names = Recipe.objects.filter(name__icontains=search_term)
    recipes = list(set(recipes_tags) | set(recipes_names))
    recipes = [{
            'id':recipe.id,
            'name':recipe.name,
            'time':recipe.time,
            'img':recipe.img,
            'avg_rating': recipe.review_set.all().aggregate(Avg('rating'))['rating__avg'] if len(recipe.review_set.all()) else 0
    } for recipe in recipes]
    restaurants = Restaurant.objects.filter(name__icontains=search_term)
    menu_items = MenuItem.objects.filter(name__icontains=search_term)
    return render(request, 'search/results.html', {
        'recipes':recipes,
        'restaurants':restaurants,
        'menu_items':menu_items,
    })

def request_data(host, path, api_key, url_params=None):

    url_params = url_params or {}
    url = '{0}{1}'.format(host, quote(path.encode('utf8')))
    headers = {
        'Authorization': 'Bearer %s' % api_key,
    }

    print(u'Querying {0} ...'.format(url))

    response = requests.request('GET', url, headers=headers, params=url_params)

    return response.json()

def fetch_data():
    category_list = [
        {'category':'italian','cuisine':'Italian'},
        {'category':'newamerican,tradamerican','cuisine':'American'},
        {'category':'indpak','cuisine':'Indian'},
        {'category':'chinese','cuisine':'Chinese'},
        {'category':'japanese,french,mexican','cuisine':'Other'},
    ]

    for category in category_list:
        url_params = {
        'term': 'restaurants',
        'location': 'New York City'.replace(' ','+'),
        'categories': category['category'],
        'limit': 10
        }
        api_key = 'jIf-E4-uxH1zRUZUNX_TyhPGMdjP8xtoEki2HrRvGeo7HMfDoB0ebjMT1hf7telobrfrhivRXzTEn47jnYugK3C8uQXAgK2bFF__Oz3ryas-lh7b3ZdkwvyG8jD8YnYx'
        restaurants_test = request_data('https://api.yelp.com','/v3/businesses/search',api_key, url_params=url_params)['businesses']

        for restaurant in restaurants_test:
            cuisine = category['cuisine']

            new_restaurant = Restaurant(
                name = restaurant['name'],
                address = restaurant['location']['display_address'][0]+', '+restaurant['location']['display_address'][1],
                phone = restaurant['display_phone'],
                cuisine = cuisine,
                desc = restaurant['url'],
                img = restaurant['image_url']
            )
            new_restaurant.save()

main_app/templates/main_app/menuitem_detail.html
{% extends 'base.html' %}
{% block content %}

<h1>{{ menuitem.name.capitalize }}</h1>
<div class="rest-info">
    <img src="{{ menuitem.img }}" class="show-img">
    <div class="rest-detail">
        <p>Restaurant: {{ menuitem.restaurant.name }}</p>
        <p>Course: {{ menuitem.course }}</p>
        <p>Price: ${{ menuitem.price }}</p>
        <p>Description: {{ menuitem.desc }}</p>
    </div>    
</div>

<h1>Related Recipes</h1>
<table class="related-recipes">
    <thead>
        <th></th>
        <th>Recipe Name</th>
        <th>Prep Time</th>
        <th>Avg Rating</th>
    </thead>
    <tbody>
        {% for recipe in recipes %}
            <tr>
                <a href="{% url 'recipes_detail' recipe.id %}">
                <td><a href="{% url 'recipes_detail' recipe.id %}"><img src="{{ recipe.img }}" class="small-img"></a></td>
                <td><a href="{% url 'recipes_detail' recipe.id %}">{{ recipe.name }}</a></td>
                <td>{{ recipe.time }}</td>
                <td>
                    {% if recipe.avg_rating >= 4.5 %} 
                        <img src="https://i.imgur.com/3We2bhe.png" alt="star" class="star">
                    {% elif recipe.avg_rating >= 3.5 %}
                        <img src="https://i.imgur.com/cj2ACch.png" alt="star" class="star">
                    {% elif recipe.avg_rating >= 2.5 %}
                        <img src="https://i.imgur.com/hreAPA8.png" alt="star" class="star">
                    {% elif recipe.avg_rating >= 1.5 %}
                        <img src="https://i.imgur.com/CihqqJW.png" alt="star" class="star">
                    {% elif recipe.avg_rating >= 0.5 %}
                        <img src="https://i.imgur.com/fKsBvRO.png" alt="star" class="star">
                    {% else %}
                        <img src="https://i.imgur.com/eyRWDnH.png" alt="star" class="star">
                    {% endif %}
                </td>
            </tr>
        {% endfor %}
    </tbody>
</table>


{% endblock %}

main_app/templates/main_app/recipe_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Recipe</h1>

  <h4 class="center-align">Are you sure you want to delete {{ object.name }}?</h4>

  <form class="center-form form" action="" method="POST">
    {% csrf_token %}
    <input class="center-align button-width" type="submit" value="Yes - Delete!" class="btn">
    <a class="center-align button-width" id="cancel" href="{% url 'recipes_detail' recipe.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/recipe_detail.html
{% extends 'base.html' %}
{% block content %}

<h1>{{ recipe.name }}</h1>
<div class="recipe-horiz">
    <div class="recipe-column recipe-detail">
        {% if user == recipe.user %}
        <div class="edit-delete">
            <a href="{% url 'recipes_update' recipe.id %}">Edit</a>
            <a href="{% url 'recipes_delete' recipe.id %}">Delete</a>
        </div>
        {% endif %}
        <img src="{{ recipe.img }}" class="show-img">
        <p>Prep Time: {{ recipe.time }}</p>
        <p>Tags: {{ recipe.tags }}</p>



    </div>
    <div class="recipe-column">
        <h2>Reviews</h2>
        {% if user.is_authenticated %}
        {% if user != recipe.user %}
            <form action="{% url 'add_reviews' recipe.id %}" method="POST">
            {% csrf_token %}
            <table class="review-form">
                {{ review_form.as_table }}
            <table>
            <input type="submit" value="Add Review">
            </form>
        {% endif %}
        {% endif %}
        <table class="recipe-reviews">
            <thead>
            <tr>
                <th class="user-column"></th>
                <th class="review-column"></th>
                <th></th>
            </tr>
            </thead>
            <tbody>
            {% for review in recipe.review_set.all %}
                <tr>
                    <td class="user-column">{{ review.user }} <br> 
                        {% if review.rating >= 4.5 %} 
                            <img src="https://i.imgur.com/3We2bhe.png" alt="star" class="star">
                        {% elif review.rating >= 3.5 %}
                            <img src="https://i.imgur.com/cj2ACch.png" alt="star" class="star">
                        {% elif review.rating >= 2.5 %}
                            <img src="https://i.imgur.com/hreAPA8.png" alt="star" class="star">
                        {% elif review.rating >= 1.5 %}
                            <img src="https://i.imgur.com/CihqqJW.png" alt="star" class="star">
                        {% elif review.rating >= 0.5 %}
                            <img src="https://i.imgur.com/fKsBvRO.png" alt="star" class="star">
                        {% else %}
                            <img src="https://i.imgur.com/eyRWDnH.png" alt="star" class="star">
                        {% endif %}
                    </td>
                    <td class="review-column">{{ review.comment }}</td>
                    <td class="delete-column">
                        {% if user == review.user %}
                        <form action="{% url 'reviews_delete' review.id %}" method="POST">
                            {% csrf_token %}
                            <input type="submit" value="X">
                        </form>
                        {% endif %}
                    </td>  
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>  
</div>
<div class="recipe-horiz">
    <div class="recipe-column">
        <h2>Ingredients</h2>
        {% if user == recipe.user %}
        <form class="ing-form" action="{% url 'add_ingredients' recipe.id %}" method="POST">
            {% csrf_token %}
            <table>
                {{ ingredient_form.as_table }}
            </table>
            <span></span>
            <input class="center-align" type="submit" value="Add Ingredient">
        </form>
        {% endif %}
        <table class="">
        <thead>
            <tr>
            <th></th>
            <th></th>
            </tr>
        </thead>
        <tbody>
            {% for ingredient in recipe.ingredient_set.all %}
            <tr>
                <td>{{ ingredient.quantity }} of {{ ingredient.name }}</td>
                <td>
                {% if user == recipe.user %}
                <form action="{% url 'ingredients_delete' ingredient.id %}" method="POST">
                    {% csrf_token %}
                    <input type="submit" value="X">
                </form>
                {% endif %}
                </td>  
            </tr>
            {% endfor %}
        </tbody>
        </table>
    </div>
    <div class="recipe-column">
        <h2>Instructions</h2>
        {% if user == recipe.user %}
        <form class="review-form ing-form" action="{% url 'add_instructions' recipe.id %}" method="POST">
            {% csrf_token %}
            <table>
                {{ instruction_form.as_table }}
            </table>
            <span></span>
            <input class="center-align" type="submit" value="Add Instruction">
        </form>
        {% endif %}  
        <table class="recipe-reviews">
            <thead>
            <tr>
                <th>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</th>
                <th></th>
                <th></th>
            </tr>
            </thead>
            <tbody>
            {% for instruction in recipe.instruction_set.all %}
                <tr>
                <td class="step-column">{{ instruction.order }}</td>
                <td>{{ instruction.step }}</td>
                <td>
                    {% if user == recipe.user %}
                    <form action="{% url 'instructions_delete' instruction.id %}" method="POST">
                        {% csrf_token %}
                        <input type="submit" value="X">
                    </form>
                    {% endif %}  
                </td>  
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}

main_app/templates/main_app/recipe_form.html
{% extends 'base.html' %}
{% block content %}

{% if object %}
    <h1>Edit {{ object.name }} </h1>
{% else %}
    <h1>Add New Recipe</h1>
{% endif %}

<div class="center-form">
    <form class="ing-form" action="" method="POST">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <span></span>
        <input class="center-align" type="submit" value="Next" class="btn">
    </form>
</div>

{% endblock %}

main_app/templates/main_app/restaurant_detail.html
{% extends 'base.html' %}
{% block content %}
<h1>{{ restaurant.name }}</h1>
<div class="rest-info">
    <img src="{{ restaurant.img }}" class="show-img">
    <div class="rest-detail">
        <p>Address: {{ restaurant.address }}</p>
        <p>Phone Number: {{ restaurant.phone }}</p>
        <p>Cuisine: {{ restaurant.cuisine }}</p>
        <a href="{{ restaurant.desc }}">{{ restaurant.name }}'s Website</a>
    </div>
</div>

<div class="flex-container">
    {% for item in restaurant.menuitem_set.all %}
    <a href="{% url 'menuitems_detail' restaurant_id=restaurant.id pk=item.id %}">
        <div>
            <p>{{ item.name }}</p>
            <img src="{{ item.img }}" class="index-img">
        </div>
    </a>
    {% endfor %}
</div>

{% endblock %}

main_app/templates/main_app/restaurant_list.html
{% extends 'base.html' %}
{% block content %}

<div class="big-container">
    <div>
        <h1>Restaurants</h1>
    </div>
    <div class="restaurant-container">
        {% for cuisine in cuisines %}
            <div class="vert-container">
                <p class="cuisines">{{ cuisine }}</p>
                {% for restaurant in restaurant_list %}
                    {% if restaurant.cuisine == cuisine %}
                    <a href="{% url 'restaurants_detail' restaurant.id %}">
                        <div class="rest-container">
                            <li>{{ restaurant.name }}</li>
                            <img src="{{ restaurant.img }}" class="index-img" alt="{{ restaurant.name }}">
                        </div>
                    </a>
                    {% endif %}
                {% endfor %}
            </div>
        {% endfor %}
    </div>
</div>

{% endblock %}